platform :ios, '15.0'
use_frameworks!

target 'demo' do
  pod 'NMSSH', '~> 2.3.1'
end

target 'demoTests' do
  inherit! :search_paths
end

target 'demoUITests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
